#+TITLE: I am not a womanizer, I promise
#+DATE: March 16, 2026

The original title for this post was actually _My first Collage_.
However, the current one is way catchier. It also reflects better the
interaction that happened during the "art class" I went a few days
ago. Without furtjer ado and no sugarcouting it, here it goes:


Yes, a lot of woman. As the art teacher said, I was being very vocal!
Ok.

**  Back to the future

Although I used a similar technique of Kafka on Metaphorsis (since I
started with the climax (damn, this is getting so uninteniontanlly
sexual)), let's go back in time to humanize myself. My therapist said
that I _need_ to humanize myself more.

The exercise started with a bunch of random magazines, paper, pens,
and utensils to paint. I thought it would be cool to just use images from the magazines.

Thanfully, no Playboy magazine was available (although vintage storages in MOntreal love them, don't ask me why since supposedly they sell 2nd hand chic clothes... _Sin City_...). But, all other magazines had a pattern. A pattern my single dude (_celibatáire_ in French, fun word, I know) easily notice: pretty woman. So, I decided to craft my collage about that.

In my defense, I started like this. On purpose, yes. Afterwall, what I want is a _wife_. See, I am not a womanizer.

More meaningful, this is how it ends. Yes, the only eldery woman on my collage haha. I am not Di Caprio and I don't apply _Di Caprio's rule_ (although my stats seem to converge to his stats lately haha)! Why did I pick this lady and I put her on top?

Because she symbolizes _the Queen_ I want in my life. And, that I want to grey with her. Finally, she is on top of *all the other ones*. Another cool detail about my craft, is the fact that I designed it to be overflowing of girls. Just like in mind. Not really in my life. Even less in my heart.

A detail noticed by my teacher was my emphasis on female lower body
haha. She did not pick elegant words, but I will keep things here
classy. Yeah, glutes & "coxudinha" are my Aquilles heels. I am
Brazilian, after all. And I _back-end_ (_back_...._end_....) software
engineer (tun tus!)!
