* First Vinyl Painting

My first vinyl painting was an attempt to mimic Katsushika Hokusai,
The Great Wave off Kanagawa, 1831. However, it was freaking horrible.

Thankfully, unlike a normal canvas, the vynil is a bless because you
can flip it and have a second try. Also, Lucas kindly went to the
workshop with me. Without him, my work would have been the worse.
Thanks for coming, brou!

Even though my first craft was a _fake wave_ (tun tuz), the second
became hipster geometry. And it still vibed with my bedroom
decoration. 

Since I love (and miss) surFew weeks ago, I had bought a nice surf
board for decoration. A good trigger of memories of an awesome trip to
Los Angeles last summer. Btw, thanks for hosting me Fiedler. Man, I do
have great friends!

Now, my room looks badass with purchased and self-made decoration.
Actually, I tried swapping my craft with a cutie who also tried a
wave. Her wave was formidable, just like her eyes. Unfortunately, she
refused my offer to exchange our works.

She says she is decisive. But, I am persistent. Vito Corleone said...
I will make her an offer she cannot refuse. _Viva L'Italia_. 


